[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit_for_nft = "GKcWYEKo8ZWKRo82e2Vgd92JwVeqwT5XNfyMmR4j4sfX"

[programs.devnet]
deposit_for_nft = "GKcWYEKo8ZWKRo82e2Vgd92JwVeqwT5XNfyMmR4j4sfX"

# [registry]
# url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
# cluster = "http://127.0.0.1:8899"
cluster = "devnet"
wallet = "/Users/taegi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
